# Name of the workflow
name: Release

# Run on every commit tag which begins with "v" (e.g. "v0.1.4")
on:
  push:
    tags:
      - "v*"

# Autmatically create a GitHub Relase, with release details specified (the relevant commits)
jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-lates"
    steps:
     - uses: "marvinpinto/action-automatic-releases@latest"
     with:
      repo_token: "${{ secrets.GITHUB_TOKEN }}"
      prerelease: false
